name: imperio
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.3
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  dio: ^5.4.3+1
  fancy_button_flutter: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mobx_codegen: ^2.6.1
  # modular_test: ^3.0.1
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/playerHome.png
    - assets/images/appleIcon.png
    - assets/images/googleIcon.png
    - assets/images/landingPageBanner.png
    - assets/images/nbaCardPlayer.png
    - assets/images/leagueCard.png
    - assets/images/championsLeagueIcon.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/core/fonts/Montserrat-Regular.ttf
          weight: 200
        - asset: lib/core/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: lib/core/fonts/Montserrat-SemiBold.ttf
          weight: 500
        - asset: lib/core/fonts/Montserrat-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
